### PR TITLE
Share Kit Objective C Library

### LINKED ISSUE #43: Share Kit for iOS (Objective-C)
Bloom is looking for great developers to help us build out the Bloom Share Kit ecosystem. Share Kit is the mechanism used for registering or authenticating on third-party websites and apps using your BloomID, providing individuals with a secure, encrypted way to access services without sharing private data, all without the need for usernames and passwords.

Share Kit can also be used to ask users for verified data where needed. For example, you could ask for a verified mobile phone number to send them SMS messages, or ask for verified data to comply with Know Your Client (KYC) regulations. It’s as easy as scanning a QR code or tapping a button!

Here is an example of how it works: https://www.youtube.com/watch?v=5bcSxy4CnfM

We have DOM and React-based libraries. Now we’re turning to the community to help us build and maintain the following Share Kit libraries. This bounty is worth 1000 DAI and needs your help!

# Share Kit Library Conversion to Objective-C Bounty

### General:
- Must expose all necessary types (if language has type system)
  - Types available [here](https://github.com/hellobloom/share-kit/blob/master/src/types.ts)
  - Interfaces available [here](https://github.com/hellobloom/share-kit/blob/master/src/util.ts) 
  - Please ensure you read and adhere to the comments in the code
- Must have adequate tests to cover the features implemented
  - Existing tests:
    - [renderRequestElement.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/renderRequestElement.test.ts) 
    - [renderRequestButton.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/elements/renderRequestButton.test.ts) 
    - [renderRequestQRCode.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/elements/renderRequestQRCode.test.ts) 
    - [util.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/util.test.ts)
- Use of a UI component framework similar to [Storybook](https://storybook.js.org/) is preferred

### Share Kit Verification Implementation Requirements:
Must expose all the same functions in [share-kit/src/utils](https://github.com/hellobloom/share-kit/blob/master/src/util.ts) and [share-kit/src/txUtils](https://github.com/hellobloom/share-kit/blob/master/src/txUtils.ts) 

### Mobile Only (e.g. Android, iOS, Flutter):
- Button:
  - Links to bloom.co/download?request={{base64 encoded request data}}&callback_url={{% encoded callback url}}
  - Has correct styling/design
    - Assets available in Bloom [Share Kit’s README.md](https://github.com/hellobloom/share-kit/blob/master/README.md) file
    - Assets should be built into the library, **no fetching from CDN or other sources**
  - Appends the query param `share-kit-from=button` to the provided requestData.url
  - Library must have the ability to update and remove the button after initial rendering
    - If applicable to the platform

## Relevant GitHub repositories:
- [Share Kit](https://github.com/hellobloom/share-kit) 
- [Receive Kit](https://github.com/hellobloom/receive-kit) 
- [Share Kit React](https://github.com/hellobloom/share-kit-react) 
- [Bloom Starter](https://github.com/hellobloom/bloom-starter)

### PR DESCRIPTION
**Pull request by mul1sh**
Fixes https://github.com/hellobloom/share-kit/issues/43

### CODE REVIEW

**Comment by edhedges** [comment]
@mul1sh I was able to used the README instructions to get a separate demo application deployed to my phone with the button properly linking in and bringing up the Sharing Request screen!

I had a couple issues with the `sharekittest.xcodeproj` which may be my own fault, but I'd like some additional clarification on how to get it working with the framework if possible. I followed the building the framework instructions for the main `sharekit.xcodeproj` project using `sharekit-universal` and a `Generic iOS Device`. Then I closed XCode and opened `sharekittest.xcodeproj` and added the embedded binary to this project just like I did to a separate demo app, but I could not get it to build. I did notice that in my separate demo app, the `sharekit.framework` folder was copied alongside my `ShareKitiOSDemo.xcodeproj` file.

**Comment by mul1sh** [comment]
@edhedges  Sorry for that, I forgot  to update the README with this because its an issue I also faced.

Basically I noticed with XCode 9 or 10 if the framework is one level higher than the directory containing the Xcode project where its been embedded, the embedding fails and you get the issue you are experiencing. I think this is a bug, though not 100% sure too, but the solution is quite simple, simply move the `sharekittest` project one level higher (i.e. your desktop )than the framework you built  and then embed it again and build and  it should work 🙂.  Let me update the README to reflect this.

**Comment by edhedges** [comment]
@mul1sh If possible, it'd be ideal to just move that test project up one level as well so that it's nicer UX for the developer.

**Comment by mul1sh** [comment]
@edhedges done, i've also included instructions on how to remove unused iOS simulator architectures from the framework when deploying an App to the iTunes app store to prevent the app from being rejected by apple.

**Comment by edhedges** [comment]
@mul1sh Just checked out the latest and it's definitely nicer that I can simply open up `sharekittest.xcodeproj` and I've got a working demo app!

**Comment by mul1sh** [comment]
@edhedges awesome 👍 🙂

**Pull request merged**
